SmartMeshFoundation/Photon

cmd/tools/smoketest/env.INI, raidenService.go, transfer/mediatedtransfer/initiator/transition.go
fix bug : #5 remove failed initiator state manager too after lock timeout
=> fix bug : #5 remove failed initiator state manager

network/codefortest.go, network/protocol.go, raidenService.go
fix #31: stop trying resend and remove mediated transfer msg if channel does't exists
=> related #31

network/rpc/contracts/TokenNetwork.sol, network/rpc/contracts/TokenNetworkRegistry.sol
Modify comments in Token.sol, TokenNetwork.sol, and TokenNetworkRegistry.sol
=> modify and add comments

blockchain/events.go, blockchain/statechangesort.go, channel/channel.go, channel/channeltype/channelstate.go, channel/channeltype/type.go
Add comments of functions in directory accounts, blockchain, channel
=> Add comments in directory accounts, blockchain, channel

mobile/api.go, network/MatrixMixTransporter.go, network/matrixtransport.go
As the title suggests，you get it.
=> add GetNotify on matrix

mobile/api.go, network/matrixcomm/matrix.go, network/matrixcomm/sync.go, network/matrixtransport.go, params/setttings.go, raidenService.go
Some problems exist in the efficiency of communication,it userd to communicate with the server frequently,it is an error.
=> Improve the efficiency of communication

codefortest.go, network/rpc/codefortest.go, raidenService.go
=> 1. test environment

cmd/smartraiden/mainimpl/impl.go, network/matrixtransport.go, params/setttings.go
Test discovery_room and user_search
=> Test discovery_room and user_search

network/MatrixPeer.go, network/gomatrix/matrix.go, network/matrixtransport.go
1. stop report duplicate status change
2. ignore invite user when startup
3. validateUsers error
=>  matrix: fix bug

network/MatrixTemporaryPeer.go, network/matrixtransport.go
1.never block send. if message chan is full, discard this message
2. support race message sending and event handling
3. temporary message room  will be removed if no message in DefaultTemporaryPeerTimeout
=> matrix function update

channel/channel.go, encoding/message.go, network/matrixtransport.go, network/protocol.go, network/xmpptransport/xmpp.go, network/xmpptransport/xmpp_test.go, raidenapi.go, restful/v1/main.go, restful/v1/transfers.go
api: ignore empty fields
protocol: make sure not block sender
xmpp: add xmpp test case
raidenapi: return error for a timeout transfer
channel: withdrawResponse process error
=> fix bugs and updates for api,protocol,xmpp and channel

docs/index.md, docs/installation_guide.md, docs/rest_api_0.8.md, docs/sm_service.md, docs/webui_tutorial.md
- channel_identifier 
- channel state
=> Update the document

docs/installation_guide.md, docs/rest_api_0.8.md
=> Update mobile devices

network/gomatrix/matrix.go, network/matrixtransport.go, network/matrixtransport_test.go
make sure the registered user must have the valid private key
=> matrix: update register 

docs/mobile_api_zh.md, docs/pfs.md, docs/pfs_online_bulletin.md, docs/pms_online_bulletin.md, docs/rest_api.md, docs/sm_service.md
update pms/pfs online bulletin  
add photon SetFeePolicy api
=> pms/pfs online bulletin 

photonService.go, restore.go
registerRegistry error should not be ignored
=> photon: fix bug: restore crash when db error.

network/rpc/client.go, photonapi.go, transfer/mediatedtransfer/mediator/mediator_test.go, transfer/mediatedtransfer/mediator/transition.go, transfer/mediatedtransfer/target/transition.go
=> bug fix and new feature

cmd/photon/mainimpl/impl.go, cmd/tools/casemanager/cases/CaseCooperateSettle.ENV, cmd/tools/casemanager/cases/CaseEthNonce.ENV, cmd/tools/casemanager/cases/CaseEthNonce.go, cmd/tools/casemanager/cases/CaseFee.ENV, cmd/tools/casemanager/cases/CaseFeeWithPFS.ENV, cmd/tools/casemanager/cases/CasePunish.ENV, cmd/tools/casemanager/cases/CaseSendTransferOnReOpenedChannel.go, cmd/tools/casemanager/cases/CaseSettle.ENV, cmd/tools/casemanager/cases/CaseTransferWithSecret.ENV, cmd/tools/casemanager/cases/CaseTransferWithSecret.go, cmd/tools/casemanager/cases/CaseWithdraw.ENV, cmd/tools/casemanager/cases/LocalCase.ENV, cmd/tools/casemanager/cases/LongCase5Nodes.ENV, cmd/tools/casemanager/models/Channel.go, cmd/tools/casemanager/models/PhotonNode.go, cmd/tools/casemanager/models/PhotonNodeApi.go, cmd/tools/casemanager/models/Req.go, cmd/tools/casemanager/models/TestEnv.go, models/gkvdb/db.go, network/rpc/client.go, pfsproxy/pfsclient.go, photonapi.go, restful/v1/main.go, restful/v1/othercontrollers.go, restful/v1/transferswithsecret.go, vendor/github.com/ethereum/go-ethereum/accounts/abi/bind/base.go
photon: default transport changed to xmpp
fix bug: block chain service race condition
=> fix bug: block chain service race condition

blockchain/events.go, channel/channel.go, cmd/tools/casemanager/cases/CaseCooperateSettle.go, cmd/tools/casemanager/cases/CaseManager.go, cmd/tools/casemanager/cases/CaseSendTransferOnReOpenedChannel.go, cmd/tools/casemanager/cases/CaseSettle.go, cmd/tools/casemanager/cases/LongCase5Nodes.ENV, cmd/tools/casemanager/cases/LongCase5Nodes.go, cmd/tools/casemanager/models/PhotonNodeApi.go, network/graph/channelgraph.go, photonService.go, transfer/mediatedtransfer/initiator/transition.go, transfer/mediatedtransfer/mediator/transition.go, transfer/mediatedtransfer/statechange.go
photonService: protocol start after handle all history event
photonService:make sure ContractHistoryEventCompleteStateChange only one time
mediatedtransfer: fix bug: initiator miss emit EventTransferSentFailed
=> photonService: protocol start after handle all history event

cmd/tools/casemanager/cases/CaseSettle.go, cmd/tools/casemanager/cases/CaseSmoke.go, network/rpc/contracts/TokensNetwork.sol
2. contract: comment of contracts
=> 1. casemanager: fix CaseSmoke bug

channel/codefortest.go, cmd/photon/mainimpl/impl.go, cmd/photon/mainimpl/main_test.go, codefortest.go, mobile/api.go, models/constant.go, models/dao.go, models/daotest/contract_call_tx_test.go, models/gkvdb/contract_call_tx.go, models/stormdb/contract_call_tx.go, models/tx.go, network/rpc/client.go, network/rpc/codefortest.go, network/rpc/secretregistryproxy.go, network/rpc/tokennetworkproxy.go, network/rpc/tokenproxy.go, notify/notifyhandler.go, photonService.go, photonapi.go, restful/v1/contract_call_tx.go, restful/v1/main.go
save all contract call tx info and add api ContractCallTXQuery
=> save contract call tx and add api for query

channel/channeltype/type.go, cmd/tools/casemanager/models/PhotonNodeApi.go, network/graph/channelgraph.go, photonapi.go, rerr/rerr_test.go, restful/v1/channels.go
=> api: openn channel return channel identifier

cmd/tools/casemanager/models/PhotonNodeApi.go
add wait time after deposit,if the balance is checked immediately, it is likely that the validation will fail.
=> add wait time after deposit

VERSION, channel/ChannelExternalState.go, channel/channel.go, cmd/tools/casemanager/cases/CaseSettle.go, cmd/tools/casemanager/models/PhotonNodeApi.go, mobile/snm.go, mobile/snm/Mortgage.go, models/tx.go, network/helper/safeethclient.go, network/rpc/tokennetworkproxy.go, photonapi.go, rerr/stderr.go
mobile: add snm
api: Settle Tx query add participant balance info
=> api: Settle Tx query add participant balance info
